main = ".open-next/worker.js"
name = "kiloshift-dashboard"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

routes = [
    { pattern = "kiloshift.gg", custom_domain = true }
]

[observability]
enabled = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
